/**
 * @file common.cpp
 * @brief A stub source file to ensure the common static library is created correctly.
 *
 * This file serves as an anchor for the CMake build system. Without at least one
 * manually created source file, the library might be considered empty, and
 * autogenerated sources (like those from Protobuf) might not be compiled.
 */

// You can leave this file completely empty, or add a simple function
// to prevent compilers from issuing warnings about empty object files.
void common_lib_anchor() {}